ProductBundle\Entity\Image:
    type: entity
    table: null
    repositoryClass: ProductBundle\Repository\ImageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        designation:
            type: string
            length: 255
        url:
            type: string
            length: 255
        alt:
            type: string
            length: 255
    manyToOne:
        product:
            targetEntity: ProductBundle\Entity\Product
            inversedBy: images
            joinColumn:
                name: product_id
                referencedColumnName: id
                nullable: false
                onDelete: RESTRICT
    lifecycleCallbacks: { }

