product_admin_image:
    resource: "@ProductBundle/Resources/config/routing/image.yml"
    prefix:   /admin/image

logout:
    path: /logout
login:
    path: /login
    defaults:
        _controller: ProductBundle:Security:login
admin:
    resource: routing/admin.yml
    prefix:   /admin

page:
    resource: routing/page.yml

