seo_index:
    path:     /
    defaults: { _controller: "ProductBundle:Seo:index" }
    methods:  GET

seo_show:
    path:     /{id}/show
    defaults: { _controller: "ProductBundle:Seo:show" }
    methods:  GET

seo_new:
    path:     /new
    defaults: { _controller: "ProductBundle:Seo:new" }
    methods:  [GET, POST]

seo_edit:
    path:     /{id}/edit
    defaults: { _controller: "ProductBundle:Seo:edit" }
    methods:  [GET, POST]

seo_delete:
    path:     /{id}/delete
    defaults: { _controller: "ProductBundle:Seo:delete" }
    methods:  DELETE
